on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to dockerhub"
        run: docker login --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}}

      - name: "build dockerhub image"
        run: docker build -t ${{secrets.USERNAME}}/task2image .

      - name: "pushing to dockerhub"
        run: docker push ${{secrets.USERNAME}}/task2image
